title: revinder
description: "Blog"
author:
  name: "Revinder"
  email: "not_giving@my.email"
  url: "https://twitter.com/Revinder_"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Revinder"
year : "2021"
